# Generated by Django 4.1.2 on 2022-10-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=15)),
                ('verified', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='user_photo/')),
            ],
        ),
    ]
