# Generated by Django 4.1.2 on 2022-11-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='walk',
            name='ending',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='walk',
            name='starting',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='walk',
            name='status',
            field=models.CharField(default='free', max_length=14),
        ),
    ]
