# Generated by Django 4.1.4 on 2022-12-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_animal_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fav_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
