# Generated by Django 4.1.4 on 2022-12-14 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_walkdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkdays',
            name='time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='walkdays',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
