# Generated by Django 4.1.4 on 2022-12-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_alter_walkdays_time_alter_walkdays_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walkdays',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='walkdays',
            name='time',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
