# Generated by Django 4.1.4 on 2022-12-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_animal_fav_count'),
        ('shelter', '0005_alter_walkdays_options_alter_walkdays_time'),
    ]

    operations = [
    ]
