# Generated by Django 4.1.4 on 2023-01-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_merge_20221214_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='block_registration',
            field=models.BooleanField(default=True),
        ),
    ]
